// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/PoolHealth/PoolHealthServer/pkg/api/v1/common"
)

type Mutation struct {
}

type Pool struct {
	ID     common.ID `json:"id"`
	Name   string    `json:"name"`
	Volume float64   `json:"volume"`
}

type Query struct {
}

type Session struct {
	Token     string    `json:"token"`
	ExpiredAt time.Time `json:"expiredAt"`
}

type Subscription struct {
}

type User struct {
	TokenExpiredAt time.Time `json:"tokenExpiredAt"`
	Pools          []*Pool   `json:"pools"`
}
