package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.62

import (
	"context"

	"github.com/vektah/gqlparser/v2/gqlerror"

	rootCommon "github.com/PoolHealth/PoolHealthServer/common"
	authPkg "github.com/PoolHealth/PoolHealthServer/internal/auth"
	"github.com/PoolHealth/PoolHealthServer/pkg/api/v1/common"
	"github.com/PoolHealth/PoolHealthServer/pkg/api/v1/graphql/generated"
	model "github.com/PoolHealth/PoolHealthServer/pkg/api/v1/models"
)

// AuthApple is the resolver for the authApple field.
func (r *mutationResolver) AuthApple(ctx context.Context, appleCode string, deviceID common.ID) (*model.Session, error) {
	session, err := r.auth.Auth(ctx, appleCode)
	if err != nil {
		return nil, gqlerror.Wrap(err)
	}
	return &model.Session{
		Token:     session.JWT,
		ExpiredAt: session.ExpiredAt,
	}, nil
}

// AddPool is the resolver for the addPool field.
func (r *mutationResolver) AddPool(ctx context.Context, name string, volume float64) (*model.Pool, error) {
	user, err := authPkg.GetUser(ctx)
	if err != nil {
		return nil, err
	}
	pool, err := r.poolData.Create(ctx, user.ID, &rootCommon.PoolData{
		Name:   name,
		Volume: volume,
	})
	if err != nil {
		return nil, castGQLError(ctx, err)
	}

	return model.PoolFromCommon(pool), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user, err := authPkg.GetUser(ctx)
	if err != nil {
		return nil, castGQLError(ctx, err)
	}
	return &model.User{TokenExpiredAt: user.Session.ExpiredAt}, nil
}

// Pools is the resolver for the pools field.
func (r *queryResolver) Pools(ctx context.Context) ([]*model.Pool, error) {
	user, err := authPkg.GetUser(ctx)
	if err != nil {
		return nil, err
	}
	pools, err := r.poolData.List(ctx, user.ID)
	if err != nil {
		return nil, castGQLError(ctx, err)
	}

	result := make([]*model.Pool, len(pools))
	for i, pool := range pools {
		result[i] = model.PoolFromCommon(&pool)
	}

	return result, nil
}

// OnCreatePool is the resolver for the onCreatePool field.
func (r *subscriptionResolver) OnCreatePool(ctx context.Context) (<-chan *model.Pool, error) {
	ch := make(chan *model.Pool)
	res, err := r.SubscribeOnCreate(ctx)
	if err != nil {
		return nil, err
	}

	go func() {
		for {
			select {
			case <-ctx.Done():
				close(ch)
			case pool := <-res:
				ch <- model.PoolFromCommon(pool)
			}
		}
	}()

	return ch, nil
}

// OnUpdatePool is the resolver for the onUpdatePool field.
func (r *subscriptionResolver) OnUpdatePool(ctx context.Context) (<-chan *model.Pool, error) {
	ch := make(chan *model.Pool)
	res, err := r.SubscribeOnUpdate(ctx)
	if err != nil {
		return nil, err
	}

	go func() {
		for {
			select {
			case <-ctx.Done():
				close(ch)
			case pool := <-res:
				ch <- model.PoolFromCommon(pool)
			}
		}
	}()

	return ch, nil
}

// OnDeletePool is the resolver for the onDeletePool field.
func (r *subscriptionResolver) OnDeletePool(ctx context.Context) (<-chan common.ID, error) {
	ch := make(chan common.ID)
	res, err := r.SubscribeOnDelete(ctx)
	if err != nil {
		return nil, err
	}

	go func() {
		for {
			select {
			case <-ctx.Done():
				close(ch)
			case id := <-res:
				ch <- common.ID(id)
			}
		}
	}()

	return ch, nil
}

// Pools is the resolver for the pools field.
func (r *userResolver) Pools(ctx context.Context, obj *model.User) ([]*model.Pool, error) {
	user, err := authPkg.GetUser(ctx)
	if err != nil {
		return nil, err
	}
	pools, err := r.poolData.List(ctx, user.ID)
	if err != nil {
		return nil, castGQLError(ctx, err)
	}

	result := make([]*model.Pool, len(pools))
	for i, pool := range pools {
		result[i] = model.PoolFromCommon(&pool)
	}

	return result, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
